# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('combo', '0002_auto_20200923_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_active', models.BooleanField(default=False, verbose_name='Preço visisvel?')),
                ('price_updated_at', models.DateTimeField(null=True)),
                ('price_published', models.DateTimeField(auto_now_add=True)),
                ('price_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_combo', to='combo.ComboModel')),
                ('price_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_service', to='service.ServiceModel')),
                ('price_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'price_list',
                'db_table': 'price_db',
            },
        ),
    ]
