# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_category', models.CharField(choices=[(None, ''), ('1', 'Noiva'), ('2', 'Formanda'), ('3', 'Debutante'), ('4', 'Independente')], default='1', max_length=1, verbose_name='Noiva, formanda ou debutante?')),
                ('bride_name', models.CharField(max_length=80, unique=True, verbose_name='Nome da noiva')),
                ('bride_party_date', models.DateField(blank=True, null=True, verbose_name='Data do evento')),
                ('bride_active', models.BooleanField(default=False, verbose_name='Noiva pronta para publicar?')),
                ('bride_updated_at', models.DateTimeField(null=True)),
                ('bride_published', models.DateTimeField(auto_now_add=True)),
                ('bride_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'bride',
                'verbose_name_plural': 'bride_list',
                'db_table': 'bride_db',
            },
        ),
    ]
