# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridemodel',
            name='bride_register_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bride_register_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bridemodel',
            name='bride_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bridemodel',
            name='bride_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bride_custom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
