# Generated by Django 3.0.4 on 2020-09-23 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_tittle', models.CharField(max_length=150, unique=True, verbose_name='Tipo de equipamento*')),
                ('equipment_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição*')),
                ('equipment_quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)], default=1, verbose_name='Quantidade deste equipamento?')),
                ('equipment_active', models.BooleanField(default=True, verbose_name='Equipamento ativo')),
                ('equipment_updated_at', models.DateTimeField(null=True)),
                ('equipment_published', models.DateTimeField(auto_now_add=True)),
                ('equipment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_user', to=settings.AUTH_USER_MODEL)),
                ('equipment_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipment_list',
                'db_table': 'equipment_db',
            },
        ),
        migrations.CreateModel(
            name='ServiceEquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_time', models.DurationField(default=datetime.timedelta(seconds=300), verbose_name='Qual tempo de uso deste equipamento? Caso seja variavel estipule um tempo minimo.')),
                ('equipment_time_exact', models.BooleanField(default=False, verbose_name='Tempo de uso deste equipamento pode variar de acordo com cada cliente?')),
                ('equipment_complement', models.BooleanField(default=False, verbose_name='Este equipamento é usado simutaniamente com algum outro equipamento?')),
                ('equipment_service_updated_at', models.DateTimeField(null=True)),
                ('equipment_service_published', models.DateTimeField(auto_now_add=True)),
                ('equipment_replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_replaced', to='equipment.EquipmentModel')),
                ('equipment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_service', to='service.ServiceModel')),
                ('equipment_service_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_equipment_author', to=settings.AUTH_USER_MODEL)),
                ('equipment_service_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment_tittle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.EquipmentModel')),
            ],
            options={
                'verbose_name': 'service_equipment',
                'verbose_name_plural': 'service_equipment_list',
                'db_table': 'service_equipment_db',
            },
        ),
    ]
