# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('service', '0001_initial'),
        ('photo', '0001_initial'),
        ('bride', '0002_auto_20200923_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_title', models.CharField(max_length=80, null=True, verbose_name='De um título para sua avaliação')),
                ('testimony_description', models.TextField(max_length=1000, null=True, verbose_name='Escreva um comentario para sua avaliação')),
                ('testimony_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('testimony_active', models.BooleanField(default=True, verbose_name='Depoimento visisvel?')),
                ('testimony_published', models.DateTimeField(auto_now_add=True)),
                ('testimony_updated_at', models.DateTimeField(null=True)),
                ('testimony_bride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimony_bride', to='bride.BrideModel')),
                ('testimony_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimony_photo', to='photo.ServicePhotoModel')),
                ('testimony_professional', models.ManyToManyField(blank=True, related_name='testimony_professional', to='professional.ProfessionalModel')),
                ('testimony_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimony_service', to='service.ServiceModel')),
                ('testimony_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('testimony_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'testimony',
                'verbose_name_plural': 'testimony_list',
                'db_table': 'testimony_db',
            },
        ),
        migrations.CreateModel(
            name='TestimonyDeletedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_deleted_date', models.DateTimeField(auto_now_add=True)),
                ('testimony_deleted_title', models.CharField(max_length=80, null=True)),
                ('testimony_deleted_description', models.TextField(max_length=1000, null=True)),
                ('testimony_deleted_rating', models.PositiveIntegerField(null=True)),
                ('testimony_deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_deleted_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'testimony_deleted',
                'verbose_name_plural': 'testimony_deleted_list',
                'db_table': 'testimony_deleted_db',
            },
        ),
    ]
