# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_service', models.CharField(max_length=100, unique=True, verbose_name='Qual nova categoria de serviços?')),
                ('category_service_published', models.DateTimeField(auto_now_add=True)),
                ('category_service_updated_at', models.DateTimeField(null=True)),
                ('category_service_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category_service_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professional_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_professional', to='professional.ProfessionalCategoryModel')),
            ],
            options={
                'verbose_name_plural': 'service_category_list',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tittle', models.CharField(max_length=150, unique=True, verbose_name='Título*')),
                ('service_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição*')),
                ('service_active', models.BooleanField(default=True, verbose_name='Serviçø inativo')),
                ('service_updated_at', models.DateTimeField(null=True)),
                ('service_published', models.DateTimeField(auto_now_add=True)),
                ('service_views', models.PositiveIntegerField(default=0)),
                ('service_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_user', to=settings.AUTH_USER_MODEL)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_category', to='service.ServiceCategoryModel')),
                ('service_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'service_list',
                'db_table': 'service_db',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalServicesSkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_extra_service', models.ManyToManyField(related_name='professional_extra_service', to='service.ServiceModel')),
                ('professional_service_in', models.ManyToManyField(related_name='professional_service_in', to='service.ServiceModel')),
                ('professional_service_out', models.ManyToManyField(related_name='professional_service_out', to='service.ServiceModel')),
                ('service_professional_skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_professional_skill', to='professional.ProfessionalModel')),
            ],
            options={
                'verbose_name': 'professional_skill',
                'verbose_name_plural': 'professional_skill_list',
                'db_table': 'professional_skill_db',
            },
        ),
    ]
