# Generated by Django 3.0.4 on 2020-09-23 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.templatetags.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(validators=[lib.templatetags.validators.validate_schedule_date], verbose_name='Qual dia você deseja agendar?')),
                ('schedule_hour', models.TimeField(default=datetime.time(0, 0), verbose_name='Qual horário você deseja agendar?')),
                ('schedule_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observações:')),
                ('schedule_service_done', models.BooleanField(default=False, verbose_name='Seviço realizado?')),
                ('schedule_service_paid', models.BooleanField(default=False, verbose_name='Seviço pago?')),
                ('schedule_updated_at', models.DateTimeField(null=True)),
                ('schedule_published', models.DateTimeField(auto_now_add=True)),
                ('schedule_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_user', to=settings.AUTH_USER_MODEL)),
                ('schedule_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_costumer', to=settings.AUTH_USER_MODEL)),
                ('schedule_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_professional', to='professional.ProfessionalModel')),
                ('schedule_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_costumer', to='service.ServiceModel')),
                ('schedule_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedule_list',
                'db_table': 'schedule_db',
            },
        ),
    ]
