# Generated by Django 3.0.4 on 2020-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='schedule_canceled',
            field=models.BooleanField(default=False, verbose_name='Seviço cancelado?'),
        ),
    ]
