# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_tittle', models.CharField(max_length=150, unique=True, verbose_name='Título do pacote*')),
                ('combo_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição do pacote*')),
                ('combo_active', models.BooleanField(default=True, verbose_name='Pacote inativo')),
                ('combo_updated_at', models.DateTimeField(null=True)),
                ('combo_published', models.DateTimeField(auto_now_add=True)),
                ('combo_expiration_date', models.DateField(blank=True, null=True)),
                ('combo_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'combo',
                'verbose_name_plural': 'combo_list',
                'db_table': 'combo_db',
            },
        ),
        migrations.CreateModel(
            name='ComboServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Quantidade de serviços?')),
            ],
            options={
                'verbose_name': 'combo_service',
                'verbose_name_plural': 'combo_service_list',
                'db_table': 'combo_service_db',
            },
        ),
    ]
