# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('combo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comboservicemodel',
            name='combo_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_service', to='service.ServiceModel'),
        ),
        migrations.AddField(
            model_name='comboservicemodel',
            name='combo_service_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_service_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comboservicemodel',
            name='combo_service_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_service_quantity', to='combo.ComboModel'),
        ),
        migrations.AddField(
            model_name='comboservicemodel',
            name='combo_service_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combomodel',
            name='combo_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combomodel',
            name='combo_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
