# Generated by Django 3.0.4 on 2020-09-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.templatetags.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_photo_file', models.FileField(blank=True, null=True, upload_to='img/service_photo_file/', validators=[lib.templatetags.validators.validate_file_extension], verbose_name='Adicione uma foto.')),
                ('service_photo_cover', models.BooleanField(default=False, verbose_name='Foto destaque?')),
                ('photo_updated_at', models.DateTimeField(null=True)),
                ('photo_published', models.DateTimeField(auto_now_add=True)),
                ('photo_expiration_date', models.DateField(blank=True, null=True)),
                ('photo_views', models.PositiveIntegerField(default=0)),
                ('photo_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photo_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_photo', to='service.ServiceModel')),
            ],
            options={
                'verbose_name': 'service_photo',
                'verbose_name_plural': 'service_photo_list',
                'db_table': 'service_photo_db',
            },
        ),
    ]
